title: "Manoel Campos Blog"
description: "Desenvolvimento de Software e Software Livre"
logo: spresso-logo.png

# Your site's domain. E.g: http://yoursite.com
url: http://manoelcampos.com
permalink: "/:year/:month/:day/:title"

# Comments in posts
comments:
    enabled: true
    disqus_shortname: manoelcampos

# Information about author
author:
    name: "Manoel Campos"
    
    # Social networks
    twitter: manoelcampos
    github: https://github.com/manoelcampos
    bitbucket:
    facebook:
    linkedin: http://linkedin.com/in/manoelcampos
    gplus:
    youtube:

# RSS feed
feed:
    max_item: 10
    
# Facebook Open Graph
open_graph:
    locale: pt_BR
    
# Code code_highlight for <pre> and <code> tags
# Powered by http://highlightjs.org/
code_highlight: true

# Site validation
google_verify: UA-2501696-2 
bing_verify:

# Page menus
top_menu:
    - { name: Home, url: / }
    - { name: "TV Digital", url: /tvd }
    - { name: Delphi, url: /delphi }
    - { name: Sistemas, url: /sistemas }
    - { name: Sobre, url: /sobre }
    - { name: Contato, url: /contato }
    
bottom_menu:
    - { name: Go to Spresso theme web, url: https://github.com/yosymfony/Spress-theme-spresso }
    
paginate: 5

exclude: ['README.md', 'LICENSE','composer.json']

google_analytics:
    id: UA-2501696-2
    site: manoelcampos.com