title: "Manoel Campos Blog"
site.title: "Manoel Campos Blog"
description: "Open source and software development"
logo: "spresso-logo.png"

# Your site's domain. E.g: http://yoursite.com
url: "http://manoelcampos.com.br"

parsedown_actived: true

# Comments in posts
comments:
    enabled: true
    disqus_shortname: "manoelcampos"

# Information about author
author:
    name: "Manoel Campos"    
    # Social networks
    twitter: "manoelcampos"
    github: "https://github.com/manoelcampos"
    bitbucket:
    facebook:
    linkedin: "http://linkedin.com/in/manoelcampos"
    gplus:
    youtube:


# Collections
collections:
  posts:
    output: true


# RSS feed
feed:
    max_item: 10

# Facebook Open Graph
open_graph:
    locale: "pt_BR"

# Code highlight for <pre> and <code> tags
# Powered by http://highlightjs.org/
code_highlight: true

# Site validation
google_verify: "UA-2501696-2"
bing_verify:

# Page menus
top_menu:
    - { name: Home, url: "/" }
    - { name: "Digital TV", url: /dtv }
    - { name: About, url: /about }

bottom_menu:
    - { name: "About", url: "http://about.me/manoelcampos" }

google_analytics:
    id: UA-2501696-2
    site: manoelcampos.com.br